### ISSUE TITLE
mina error invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by udomsak** [mina-deploy/mina#360]
When i wrote task with and run first time 

```
queue! "if [ ! -d #{deploy_to}/#{shared_path}/wp-content ]; then mv -v #{deploy_to}/#{current_path}/wp-content #{deploy_to}/#{shared_path}/ ; fi"
```
then mina will raise error 

```
mina aborted!
invalid byte sequence in US-ASCII
/usr/local/bundle/gems/mina-0.3.7/lib/mina/output_helpers.rb:23:in `print_str'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/output_helpers.rb:41:in `print_char'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/exec_helpers.rb:29:in `block (2 levels) in pretty_system'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/exec_helpers.rb:104:in `stream_stdout'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/exec_helpers.rb:29:in `block in pretty_system'
/usr/local/bundle/gems/open4-1.3.4/lib/open4.rb:111:in `call'
/usr/local/bundle/gems/open4-1.3.4/lib/open4.rb:111:in `do_popen'
/usr/local/bundle/gems/open4-1.3.4/lib/open4.rb:34:in `popen4'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/tools.rb:11:in `popen4'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/exec_helpers.rb:20:in `pretty_system'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/ssh_helpers.rb:97:in `invoke'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/ssh_helpers.rb:36:in `ssh'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/helpers.rb:60:in `block in run!'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/helpers.rb:104:in `measure'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/helpers.rb:93:in `report_time'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/helpers.rb:60:in `run!'
/usr/local/bundle/gems/mina-0.3.7/lib/mina/helpers.rb:115:in `mina_cleanup!'
/usr/local/bundle/gems/mina-0.3.7/bin/mina:55:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/usr/local/bundle/gems/mina-0.3.7/bin/mina:26:in `block in <top (required)>'
/usr/local/bundle/gems/mina-0.3.7/bin/mina:25:in `instance_eval'
/usr/local/bundle/gems/mina-0.3.7/bin/mina:25:in `<top (required)>'
/usr/local/bundle/bin/mina:23:in `load'
/usr/local/bundle/bin/mina:23:in `<main>'

```

But when i run mina second  the everything is fine 

## My env
-  mina version : version v0.3.7
-  ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]

**Comment by udomsak** [comment]
The issue is set  locale  LANG=en.US-UTF-8

**Comment by czj** [comment]
We had the same issue with a deployment recently where, during Rails' asset pipeline compilation, this exception popped on macOS Mojave or High Sierra.

We had to remove this from our fish config (or zsh / bash) :

```shell
set -gx LC_ALL "en_US.utf8"
```

And use this instead, without any encoding specified :

```shell
set -gx LC_ALL "en_US"
```
