### ISSUE TITLE
rbenv/mina Permission denied @ rb_sysopen - /etc/init/app.conf (Errno::EACCES)

### ISSUE THREAD

**Issue by dcalixto** [mina-deploy/mina#399]
**Someone knows how to give rbenv permission to mina/foreman export?
thank's**

```
[foreman export] writing: app.conf
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/export/base.rb:162:in `initialize': Permission denied @ rb_sysopen - /etc/init/app.conf (Errno::EACCES)
	from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/export/base.rb:162:in `open'
	from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/export/base.rb:162:in `write_file'
	from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/export/base.rb:139:in `write_template'
	from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/export/upstart.rb:12:in `export'
	from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/lib/foreman/cli.rb:61:in `export'
	from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foreman-0.82.0/bin/foreman:7:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/2.2.2/bin/foreman:23:in `load'
	from /home/ubuntu/.rbenv/versions/2.2.2/bin/foreman:23:in `<main>'

```

**Comment by d4be4st** [comment]
Please redirect this issue to https://github.com/mina-deploy/mina-foreman as we moved this plugin to its own repository
