### ISSUE TITLE
Undefined method 'to'  for main:Object

### ISSUE THREAD

**Issue by activestylus** [mina-deploy/mina#454]
I'm on El Capitan 10.11.6 and can't seem to get mina working (version v1.0.0)

Dev tools are installed and my app works locally, but deploying fails:

```
** Invoke deploy (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute deploy
** Invoke environment
** Invoke git:clone (first_time)
** Execute git:clone
** Invoke deploy:link_shared_paths (first_time)
** Execute deploy:link_shared_paths
** Invoke bundle:install (first_time)
** Execute bundle:install
** Invoke rails:db_migrate (first_time)
** Execute rails:db_migrate
** Invoke rails:assets_precompile (first_time)
** Execute rails:assets_precompile
mina aborted!
NoMethodError: undefined method `to' for main:Object
/Users/home/apps/myapp/config/deploy.rb:62:in `block (2 levels) in <top (required)>'
/Users/home/apps/myapp/vendor/cache/mina-3a23fce25dd4/lib/mina/helpers/internal.rb:7:in `deploy_script'
/Users/home/apps/myapp/vendor/cache/mina-3a23fce25dd4/lib/mina/dsl.rb:50:in `block in deploy'
/Users/home/apps/myapp/vendor/cache/mina-3a23fce25dd4/lib/mina/dsl.rb:29:in `run'
/Users/home/apps/myapp/vendor/cache/mina-3a23fce25dd4/lib/mina/dsl.rb:49:in `deploy'
/Users/home/apps/myapp/config/deploy.rb:53:in `block in <top (required)>'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/home/.rvm/myapp/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/home/apps/myapp/vendor/cache/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/home/apps/myapp/vendor/cache/mina-3a23fce25dd4/lib/mina/application.rb:16:in `run'
/Users/home/apps/myapp/vendor/cache/mina-3a23fce25dd4/bin/mina:4:in `<top (required)>'
/Users/home/.rvm/myapp/ruby-2.3.1/bin/mina:22:in `load'
/Users/home/.rvm/myapp/ruby-2.3.1/bin/mina:22:in `<main>'
/Users/home/.rvm/myapp/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/home/.rvm/myapp/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => deploy
```

**Comment by activestylus** [comment]
A stripped down copy of my deploy.rb for reference:

```
require 'mina/bundler'
require 'mina/rails'
require 'mina/git'
require 'mina/rvm'    
set :domain,        '11.111.111.111'
set :port,          '20' 
set :user,          'deploy'
set :identity_file, '/Users/home/.ssh/id_rsa'
set :deploy_to,     '/home/deploy/www/app'
set :repository,    "/home/deploy/repos/app.git"
set :branch,        'master'
set :shared_paths, [
  'config/database.yml',
  'log/production.log',
  'log/unicorn.log',
  'public/system',
  'tmp'
]
task :environment do
  invoke :'rvm:use[ruby-2.1.2@default]'
end
set :rvm_path, '/home/deploy/.rvm/bin/rvm'
task :setup => :environment do
  queue! %[mkdir -p "#{deploy_to}/#{shared_path}/log"]
  queue! %[chmod g+rx,u+rwx "#{deploy_to}/#{shared_path}/log"]
  queue! %[mkdir -p "#{deploy_to}/#{shared_path}/config"]
  queue! %[chmod g+rx,u+rwx "#{deploy_to}/#{shared_path}/config"]
end

desc "Deploys the current version to the server."
task :deploy => :environment do
  deploy do
    invoke :'git:clone'
    invoke :'deploy:link_shared_paths'
    invoke :'bundle:install'
    invoke :'rails:db_migrate'
    invoke :'rails:assets_precompile'
    invoke :'deploy:cleanup'
    to :launch do
      queue 'touch tmp/restart.txt'
    end
  end
end
task :'deploy:code' do
  invoke :'git:clone'
  invoke :'deploy:link_shared_paths'
end
task :'deploy:thin' do
  queue "pkill -f thin"
  queue 'bundle exec thin start -C /etc/thin/myapp.yml'
end
```

**Comment by activestylus** [comment]
Also, I tried this on Ruby 1.9.3, 2.1.2 and 2.2.1  to no avail. Same error every time. Odd!

**Comment by d4be4st** [comment]
https://github.com/mina-deploy/mina/blob/master/docs/migrating.md

**Comment by activestylus** [comment]
Thanks so much! I did not realize the recent version had breaking changes

**Comment by bbnnt** [comment]
that is, pkill seems to break whatever's done
