### ISSUE TITLE
webpacker emoji character error

### ISSUE THREAD

**Issue by vonchristian** [mina-deploy/mina#633]
I am trying to deploy an app with webpacker and this occurs. I think it has to do with webpacker showing emojis on the terminal.

$ RAILS_ENV="production" bundle exec rake webpacker:compile
#<Thread:0x00007fc63ba3d2d0@/Users/von-christian/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mina-1.2.3/lib/mina/runner/pretty.rb:19 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        2: from /Users/von-christian/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mina-1.2.3/lib/mina/runner/pretty.rb:21:in `block (2 levels) in run'
        1: from /Users/von-christian/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mina-1.2.3/lib/mina/helpers/output.rb:6:in `print_line'
/Users/von-christian/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mina-1.2.3/lib/mina/helpers/output.rb:6:in `===': invalid byte sequence in US-ASCII (ArgumentError)
#<Thread:0x00007fc63ba3d1e0@/Users/von-christian/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mina-1.2.3/lib/mina/runner/pretty.rb:25 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /Users/von-christian/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mina-1.2.3/lib/mina/runner/pretty.rb:26:in `block (2 levels) in run'
/Users/von-christian/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/mina-1.2.3/lib/mina/runner/pretty.rb:26:in `gets': stream closed in another thread (IOError)
mina aborted!
ArgumentError: invalid byte sequence in US-ASCII

Tasks: TOP => deploy
(See full trace by running task with --trace)

**Comment by vonchristian** [comment]
I've added
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
to my ~/.profile 

the emojis are now showing.
